"""rename_assignment_to_deployment_add_deployed_dashboard_id

Revision ID: 17fe7e363a62
Revises: d90ad4d831cd
Create Date: 2026-04-14 11:48:51.838259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17fe7e363a62'
down_revision = 'd90ad4d831cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composed_dashboard_deployments',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('composed_dashboard_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('last_deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deployed_dashboard_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['composed_dashboard_id'], ['composed_dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deployed_dashboard_id'], ['dashboards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('composed_dashboard_id', 'organization_id', name='uq_composed_dashboard_deployment')
    )
    op.drop_table('composed_dashboard_assignments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composed_dashboard_assignments',
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('composed_dashboard_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_deployed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['composed_dashboard_id'], ['composed_dashboards.id'], name='composed_dashboard_assignments_composed_dashboard_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='composed_dashboard_assignments_organization_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='composed_dashboard_assignments_pkey'),
    sa.UniqueConstraint('composed_dashboard_id', 'organization_id', name='uq_composed_dashboard_assignment')
    )
    op.drop_table('composed_dashboard_deployments')
    # ### end Alembic commands ###
