"""add_template_ids_to_metr_models

Revision ID: 336b49ee8782
Revises: 17fe7e363a62
Create Date: 2026-04-23 15:10:34.187976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336b49ee8782'
down_revision = '17fe7e363a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metr_data_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('template_ds_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metr_data_source_data_source_id'), 'metr_data_source', ['data_source_id'], unique=True)
    op.create_index(op.f('ix_metr_data_source_org_id'), 'metr_data_source', ['org_id'], unique=False)
    op.create_table('metr_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('template_query_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metr_query_org_id'), 'metr_query', ['org_id'], unique=False)
    op.create_index(op.f('ix_metr_query_query_id'), 'metr_query', ['query_id'], unique=True)
    op.add_column('metr_dashboard', sa.Column('template_dashboard_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metr_dashboard', 'template_dashboard_id')
    op.drop_index(op.f('ix_metr_query_query_id'), table_name='metr_query')
    op.drop_index(op.f('ix_metr_query_org_id'), table_name='metr_query')
    op.drop_table('metr_query')
    op.drop_index(op.f('ix_metr_data_source_org_id'), table_name='metr_data_source')
    op.drop_index(op.f('ix_metr_data_source_data_source_id'), table_name='metr_data_source')
    op.drop_table('metr_data_source')
    # ### end Alembic commands ###
