"""add template_query_id to MetrQuery sidecar table

Revision ID: 4542a358a322
Revises: bcf5aabfe7f7
Create Date: 2026-08-03 16:09:49.723965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4542a358a322'
down_revision = 'bcf5aabfe7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metr_query', sa.Column('template_query_id', sa.Integer(), nullable=True))
    op.create_index('uq_metr_query_org_template_query_id', 'metr_query', ['org_id', 'template_query_id'], unique=True, postgresql_where=sa.text('template_query_id IS NOT NULL'))
    op.create_foreign_key('metr_query_template_query_id_fkey', 'metr_query', 'queries', ['template_query_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('metr_query_template_query_id_fkey', 'metr_query', type_='foreignkey')
    op.drop_index('uq_metr_query_org_template_query_id', table_name='metr_query', postgresql_where=sa.text('template_query_id IS NOT NULL'))
    op.drop_column('metr_query', 'template_query_id')
    # ### end Alembic commands ###
