"""create_metr_dashboard

Revision ID: 49b621717015
Revises: 2280e66fca00
Create Date: 2026-02-18 11:21:26.121034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b621717015'
down_revision = '2280e66fca00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metr_dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('url_identifier', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metr_dashboard_dashboard_id'), 'metr_dashboard', ['dashboard_id'], unique=True)
    op.create_index(op.f('ix_metr_dashboard_org_id'), 'metr_dashboard', ['org_id'], unique=False)
    op.create_index('uq_metr_dashboard_org_url_identifier', 'metr_dashboard', ['org_id', 'url_identifier'], unique=True, postgresql_where=sa.text('url_identifier IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_metr_dashboard_org_url_identifier', table_name='metr_dashboard', postgresql_where=sa.text('url_identifier IS NOT NULL'))
    op.drop_index(op.f('ix_metr_dashboard_org_id'), table_name='metr_dashboard')
    op.drop_index(op.f('ix_metr_dashboard_dashboard_id'), table_name='metr_dashboard')
    op.drop_table('metr_dashboard')
    # ### end Alembic commands ###
