"""create_metr_query_and_add_allowed_widget_query_identifier

Revision ID: 66335454929d
Revises: 49b621717015
Create Date: 2026-05-27 23:09:39.303308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66335454929d'
down_revision = '49b621717015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metr_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('query_identifier', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metr_query_org_id'), 'metr_query', ['org_id'], unique=False)
    op.create_index(op.f('ix_metr_query_query_id'), 'metr_query', ['query_id'], unique=True)
    op.create_index('uq_metr_query_org_query_identifier', 'metr_query', ['org_id', 'query_identifier'], unique=True, postgresql_where=sa.text('query_identifier IS NOT NULL'))
    op.add_column('metr_dashboard', sa.Column('allowed_widget_query_identifier', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metr_dashboard', 'allowed_widget_query_identifier')
    op.drop_index('uq_metr_query_org_query_identifier', table_name='metr_query', postgresql_where=sa.text('query_identifier IS NOT NULL'))
    op.drop_index(op.f('ix_metr_query_query_id'), table_name='metr_query')
    op.drop_index(op.f('ix_metr_query_org_id'), table_name='metr_query')
    op.drop_table('metr_query')
    # ### end Alembic commands ###
