"""create metrWidget having tags and related 1to1 to Widget

Revision ID: 6f3ff3d0dd48
Revises: 7205816877ec
Create Date: 2024-09-13 12:25:29.204711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f3ff3d0dd48'
down_revision = '7205816877ec'
branch_labels = ('metrWidgets',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrwidgets',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Unicode()), nullable=True),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrwidgets')
    # ### end Alembic commands ###
