"""DashboardGroup should always offer view_only access fo now

Revision ID: 863b2d58a30f
Revises: c84bc5e8cd5b
Create Date: 2025-02-20 17:33:04.704123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863b2d58a30f'
down_revision = 'c84bc5e8cd5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard_groups', 'view_only')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_groups', sa.Column('view_only', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
