"""add Composed Dashboard and necessary Deployment tables

Revision ID: bcf5aabfe7f7
Revises: 666406e70679
Create Date: 2026-08-03 10:42:22.437991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf5aabfe7f7'
down_revision = '666406e70679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composed_dashboards',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_identifier', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_identifier')
    )
    op.create_table('composed_dashboard_deployments',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('composed_dashboard_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('last_deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['composed_dashboard_id'], ['composed_dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('composed_dashboard_id', 'organization_id', name='uq_composed_dashboard_deployment')
    )
    op.create_table('composed_dashboard_entries',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('composed_dashboard_id', sa.Integer(), nullable=False),
    sa.Column('template_dashboard_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composed_dashboard_id'], ['composed_dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('composed_dashboard_id', 'template_dashboard_id', name='uq_composed_dashboard_entry')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('composed_dashboard_entries')
    op.drop_table('composed_dashboard_deployments')
    op.drop_table('composed_dashboards')
    # ### end Alembic commands ###
