"""fix fk in DashboardGroup table

Revision ID: c84bc5e8cd5b
Revises: 4f2f08518234
Create Date: 2025-02-18 12:08:41.618060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84bc5e8cd5b'
down_revision = '4f2f08518234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dashboard_groups', 'dashboard_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dashboard_groups', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dashboard_groups', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dashboard_groups', 'dashboard_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
